name: build

on:
  push:
    branches:
      - 'build-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.ref }}
      - run: ./scripts/preBuild.sh
      - run: node test.js
      - run: ./scripts/postBuild.sh
