name: build

on:
  push:
    branches:
      - 'build-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install -r requirements.txt 
      - uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-build-${{ github.ref }}
      - run: ./scripts/init_cds.sh
          env:
            CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
      - run: ./scripts/build.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: cache
          path: cache/