name: start-build

on:
  push:
    branches:
      - 'build-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-node-modules-${{ env.GITHUB_REF }}
      - run: ./scripts/preBuild.sh
      - run: node test.js
      - run: ./scripts/postBuild.sh
